In [17]:
import numpy as np
from scipy.spatial import distance

nn = np.array([])
maxd = .7072

basis = np.array([[0, 0, 0],[0.5,0.5,0],[0,0.5,0.5],[0.5,0,0.5]])
origin = np.array([[ 0, 0, 0]])
data = np.array([[0.5,0.5,0],[0,0.5,0.5],[0.5,0,0.5],[1,0,0],[1.5,0.5,0],[1,0.5,0.5],[1.5,0,0.5],
            [0,1.5,0.5],[0.5,1,0.5],[0,0,1],[0.5,0.5,1],[0,0.5,1.5],[0.5,0,1.5],[2,0,0],[2.5,0.5,0],
            [2,0.5,0.5],[2.5,0,0.5],[0,2,0],[0.5,2.5,0],[0,2.5,0.5],[0.5,2,0.5],[0,0,2],[0.5,0.5,2],
            [0,0.5,2.5],[0.5,0,2.5],[-1,0,0],[-0.5,0.5,0],[-1,0.5,0.5],[-0.5,0,0.5],[0,-1,0],[0.5,-0.5,0],
            [0,-0.5,0.5],[0.5,-1,0.5],[0,0,-1],[0.5,0.5,-1],[0,0.5,-0.5],[0.5,0,-0.5],[-2,0,0],[-1.5,0.5,0],
            [-2,0.5,0.5],[-1.5,0,0.5],[0,-2,0],[0.5,-1.5,0],[0,-1.5,0.5],[0.5,-2,0.5],[0,0,-2],[0.5,0.5,-2],
            [0,0.5,-1.5],[0.5,0,-1.5]]) 


distance = distance.cdist(data, origin, 'euclidean')
n = 0
for point in range(len(distance)):
    if distance[point]<=maxd:
        print(origin, 'and', data[point], 'are Nearest Neighbors! YAY')

[[0 0 0]] and [0.5 0.5 0. ] are Nearest Neighbors! YAY
[[0 0 0]] and [0.  0.5 0.5] are Nearest Neighbors! YAY
[[0 0 0]] and [0.5 0.  0.5] are Nearest Neighbors! YAY
[[0 0 0]] and [-0.5  0.5  0. ] are Nearest Neighbors! YAY
[[0 0 0]] and [-0.5  0.   0.5] are Nearest Neighbors! YAY
[[0 0 0]] and [ 0.5 -0.5  0. ] are Nearest Neighbors! YAY
[[0 0 0]] and [ 0.  -0.5  0.5] are Nearest Neighbors! YAY
[[0 0 0]] and [ 0.   0.5 -0.5] are Nearest Neighbors! YAY
[[0 0 0]] and [ 0.5  0.  -0.5] are Nearest Neighbors! YAY
