In [1]:
from sys import argv
import numpy as np

basis = np.array([[0,0,0], [0.5,0.5,0], [0,0.5,0.5], [0.5,0,0.5]])
uvector = np.eye(3)
coords = []

lower = -2
upper = 2

for n in np.arange(lower, upper+1):
	for i in np.arange(0, 3):
		coords.append(np.add(n*uvector[i], basis))

coords = np.array(coords)
s = coords.shape
coords = coords.reshape((s[0]*s[1], s[2]))

def euclidean_dist(x, y):
	return np.sqrt(np.sum(np.power(x-y, 2)))

nn = []

origin = np.array([0,0,0])

for c in coords:
	d = euclidean_dist(origin, c)
	print("%s and %s = %s"%(origin, c, d))
	if d <= 0.7072:
		# print("This one:", c, "!!!")
		nn.append(c)

# nn = np.unique(nn, axis=0)
print("Number of elements:", len(nn))
print("Elements:", nn)

[0 0 0] and [-2.  0.  0.] = 2.0
[0 0 0] and [-1.5  0.5  0. ] = 1.5811388300841898
[0 0 0] and [-2.   0.5  0.5] = 2.1213203435596424
[0 0 0] and [-1.5  0.   0.5] = 1.5811388300841898
[0 0 0] and [ 0. -2.  0.] = 2.0
[0 0 0] and [ 0.5 -1.5  0. ] = 1.5811388300841898
[0 0 0] and [ 0.  -1.5  0.5] = 1.5811388300841898
[0 0 0] and [ 0.5 -2.   0.5] = 2.1213203435596424
[0 0 0] and [ 0.  0. -2.] = 2.0
[0 0 0] and [ 0.5  0.5 -2. ] = 2.1213203435596424
[0 0 0] and [ 0.   0.5 -1.5] = 1.5811388300841898
[0 0 0] and [ 0.5  0.  -1.5] = 1.5811388300841898
[0 0 0] and [-1.  0.  0.] = 1.0
[0 0 0] and [-0.5  0.5  0. ] = 0.7071067811865476
[0 0 0] and [-1.   0.5  0.5] = 1.224744871391589
[0 0 0] and [-0.5  0.   0.5] = 0.7071067811865476
[0 0 0] and [ 0. -1.  0.] = 1.0
[0 0 0] and [ 0.5 -0.5  0. ] = 0.7071067811865476
[0 0 0] and [ 0.  -0.5  0.5] = 0.7071067811865476
[0 0 0] and [ 0.5 -1.   0.5] = 1.224744871391589
[0 0 0] and [ 0.  0. -1.] = 1.0
[0 0 0] and [ 0.5  0.5 -1. ] = 1.224744871391589
[0 0 0] and